src/BookAdvertisement/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import get_all_ads, get_ad_info, AdCreate, AdUpdate, AdDelete, \
    get_all_pending_ads_for_admin, update_ad_status

app_name = 'BookAdvertisement'

urlpatterns = [
    path('', get_all_ads, name='all-ads'),
    path('pending/', get_all_pending_ads_for_admin, name='all-pending-ads'),
    path('pending/<int:ad_id>/<str:accept>/', update_ad_status, name='update-pending-ad-status'),
    path('<int:pk>/', get_ad_info, name='ad'),
    path('<int:pk>/edit', login_required(AdUpdate.as_view()), name='ad-update'),
    path('<int:pk>/delete', login_required(AdDelete.as_view()), name='ad-delete'),
    path('new/', login_required(AdCreate.as_view()), name='ad-new'),
]

src/napela/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('chat/', include('chat_channel.urls')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ads/', include('BookAdvertisement.urls', namespace='BookAdvertisement')),
                  path('score/', include('user_score.urls', namespace='user_score')),
                  path('', include('home_page.urls', namespace='home_page'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_score/urls.py
from django.urls import path

from .views import set_advertisement_addresser_and_done, give_score

app_name = 'user_score'

urlpatterns = [
    path('set-addresser/<int:ad_id>/', set_advertisement_addresser_and_done, name='set_addresser_and_done'),
    path('give-score/<int:ad_id>/', give_score, name='give_score'),
]

src/BookAdvertisement/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext as _


class BookAd(models.Model):
    class AdStatus(models.TextChoices):
        PENDING = "PENDING",
        ACCEPTED = "ACCEPTED",
        REJECTED = "REJECTED",
        DONE = "DONE"

        @classmethod
        def choices(cls):
            print(tuple((i.name, i.value) for i in cls))
            return tuple((i.name, i.value) for i in cls)

    owner = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    poster = models.ImageField("تصویر", upload_to='ad_posters/', null=True, blank=True)
    title = models.CharField("نام کتاب", max_length=30, blank=False)
    author = models.CharField("نام نویسنده", max_length=30)
    description = models.TextField("توضیحات", max_length=500)
    sell = models.BooleanField("فروشی")
    suggested_money = models.IntegerField(verbose_name=_('suggested money'), default=0, null=False)
    status = models.CharField(max_length=255, choices=AdStatus.choices, verbose_name='status', default=AdStatus.PENDING)
    created_datetime = models.DateTimeField(null=False, auto_now_add=True, )
    modified_datetime = models.DateTimeField(null=False, default=timezone.datetime(year=2020, month=1, day=1))
    # scoring fields
    addresser = models.ForeignKey(User, blank=True, null=True, on_delete=models.DO_NOTHING, related_name="addresser")

    def __str__(self):
        return self.title

    def owner_score(self):
        all_ads = BookAd.objects.filter(owner=self.owner)
        scores = []
        for ad in all_ads:
            try:
                score = ad.advertisement.score
                scores.append(score)
            except:
                pass
        if len(scores) == 0:
            return "5.0"
        return "%.1f" % (sum(scores) / len(scores))

    def get_absolute_url(self):
        return reverse('BookAdvertisement:ad', kwargs={'pk': self.pk})

    def clean(self):
        if self.poster and not self.sell:
            raise ValidationError("posters are not allowed for buy advertisements")

    def save(self, *args, **kwargs):
        self.full_clean()
        return super(BookAd, self).save(*args, **kwargs)

src/BookAdvertisement/views.py
from copy import deepcopy

from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.exceptions import PermissionDenied
from django.db import models
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import BookAd

links = [{"href": "/", "class": "item", "title": "صفحه اصلی"},
         {"href": "/ads", "class": "item", "title": "آگهی‌ها"},
         {"href": "/ads/new", "class": "item", "title": "ثبت آگهی"}]


def get_all_ads(request):
    filter_params = dict()
    for key in request.GET:
        attr = getattr(BookAd, key, None)
        if attr and isinstance(attr.field, models.IntegerField):
            filter_params[key] = int(request.GET[key])
        else:
            filter_params[key] = request.GET[key]

    template_name = 'all_ads.html'
    queryset = BookAd.objects.filter(status=BookAd.AdStatus.ACCEPTED) \
        .filter(**filter_params)
    temp_links = deepcopy(links)
    temp_links[1]["class"] = "active item"
    context = {"page_title": "کلیه‌ی آگهی‌ها", "book_ads": queryset, "links": temp_links}
    return render(request, template_name, context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def update_ad_status(request, ad_id, accept):
    add = get_object_or_404(BookAd, pk=ad_id)
    add.status = accept
    add.save()
    return HttpResponseRedirect(reverse('BookAdvertisement:all-pending-ads'))


@login_required
@user_passes_test(lambda u: u.is_superuser)
def get_all_pending_ads_for_admin(request):
    template_name = 'BookAdvertisement/ad_admin_accepting_list.html'
    queryset = BookAd.objects.filter(status=BookAd.AdStatus.PENDING)
    temp_links = deepcopy(links)
    temp_links[1]["class"] = "active item"
    context = {"page_title": "کلیه‌ی آگهی‌ها در در انتظار تایید", "book_ads": queryset, "links": temp_links}
    return render(request, template_name, context)


def get_ad_info(request, pk):
    template_name = 'ad_info.html'
    ad: BookAd = get_object_or_404(BookAd, pk=pk)
    owner_score = ad.owner_score()
    temp_links = deepcopy(links)
    context = {"page_title": "اطلاعات آگهی", "ad": ad, "links": temp_links, "owner_score": owner_score}
    return render(request, template_name, context)


class AdCreate(CreateView):
    model = BookAd
    fields = ['poster', 'title', 'author', 'description', 'sell', 'suggested_money']

    def form_valid(self, form):
        from datetime import datetime, timezone
        # checking ad limit for user
        book_ads = BookAd.objects.filter(owner=self.request.user).order_by('created_datetime')
        now = datetime.now(timezone.utc)
        if book_ads.count() < 3 or (now - book_ads[book_ads.count() - 3].created_datetime).days > 30:
            from datetime import datetime
            obj: BookAd = form.save(commit=False)
            obj.owner = self.request.user
            obj.created_datetime = datetime.now()
            obj.save()
            return HttpResponseRedirect(obj.get_absolute_url())
        else:
            # creation is not allowed
            title = "محدودیت آگهی"
            description = "سلام کاربر گرامی!" + "\n" + "هر کاربر در ماه تنها دسترسی به انتشار سه اگهی را دارد."
            link_redirect = ""
            return render(self.request, "BookAdvertisement/apply_information_page.html",
                          {'title': title, 'description': description, 'link_redirect': link_redirect})

    def get_context_data(self, **kwargs):
        ctx = super(AdCreate, self).get_context_data(**kwargs)
        temp_links = deepcopy(links)
        temp_links[2]["class"] = "active item"
        ctx['links'] = temp_links
        ctx["page_title"] = "آگهی جدید"
        ctx["nav"] = "آگهی جدید"
        return ctx


class AdUpdate(UpdateView):
    model = BookAd
    fields = ['poster', 'title', 'author', 'description', 'sell', 'suggested_money']

    def form_valid(self, form):
        from django.utils import timezone
        obj: BookAd = form.save(commit=False)
        if obj.owner == self.request.user:
            obj.owner = self.request.user
            obj.modified_datetime = timezone.datetime.now()
            obj.save()
            return HttpResponseRedirect(obj.get_absolute_url())
        else:
            raise PermissionDenied()

    def get_context_data(self, **kwargs):
        ctx = super(AdUpdate, self).get_context_data(**kwargs)
        temp_links = deepcopy(links)
        ctx['links'] = temp_links
        ctx["page_title"] = "ویرایش آگهی"
        ctx["nav"] = "ویرایش آگهی"
        return ctx


class AdDelete(DeleteView):
    model = BookAd
    success_url = reverse_lazy('BookAdvertisement:all-ads')

    def get_context_data(self, **kwargs):
        ctx = super(AdDelete, self).get_context_data(**kwargs)
        temp_links = deepcopy(links)
        ctx['links'] = temp_links
        ctx["page_title"] = "delete ad"
        return ctx

src/BookAdvertisement/templates/ad_info.html
{% extends 'base.html' %}
{% load static %}


{% block extra_header %}
<link rel="stylesheet" type="text/css" href="{% static 'css/ad_info.css' %}"/>
{% endblock %}

{% block content %}
<div class="ui container">
    <div class="ui message">
        <h1 class="ui huge header">کتاب‌باز</h1>
        <p style="font-family: iransansdn; font-weight: bold" class="lead">
            مکانی برای تبادل کتاب های شما
        </p>
    </div>
</div>

<div class="ui divider"></div>

<div class="ui container">
    <div class="ui relaxed divided items">
        <!--  author title + sell/buy -->
        <div class="item">
            <div class="content" dir="rtl">
                <a class="ui large header">{{ ad.title }}</a>
                <div class="meta" dir="rtl">
                    {% if ad.status == "PENDING" %}
                    <div class="ui label">درانتظار تایید</div>
                    {% elif ad.status == "REJECTED" %}
                    <div class="ui label">رد شده</div>
                    {% elif ad.status == "ACCEPTED" %}
                    <div class="ui label">تایید شده</div>
                    {% endif %}
                </div>
                <div class="meta" dir="rtl">
                    {% if ad.sell %}
                    <div class="ui label">فروش</div>
                    {% else %}
                    <div class="ui label">خرید</div>
                    {% endif %}
                    <a>{{ ad.author }}</a>
                </div>
            </div>
        </div>

        <!-- other information about the book -->
        <div class="item">
            <!-- book image -->
            <div class="ui medium image">
                {% if ad.poster.url is not None %}
                <img src="{{ ad.poster.url }}" alt="image">
                {% else %}
                <img class="info_container__image" src="{% static 'images/default.jpg' %}" alt="image">
                {% endif %}
            </div>

            <!-- general information -->
            <div class="ui text container float right">
                <div class="ui segments">
                    <div class="ui segment" dir="rtl">
                        {% if ad.owner is not None %}
                        <strong>آگهی‌دهنده</strong>
                        <strong>{{ ad.owner.first_name }} {{ ad.owner.first_name }} </strong>
                        <strong>با نام کاربری</strong>
                        <strong>{{ ad.owner.username }}</strong>
                        {% endif %}
                    </div>
                    <div class="ui segment" dir="rtl">
                        <strong>امتیاز کلی صاحب آگهی:</strong>
                        <strong>{{ owner_score }}</strong>

                    </div>
                    <div class="ui segment" dir="rtl">
                        <strong>شماره تماس:</strong>
                        <strong>{{ ad.owner.profile.phone_number }}</strong>

                    </div>
                    <div class="ui segment" dir="rtl">
                        <strong>رشته:</strong>
                        <strong>{{ ad.owner.profile.field }}</strong>
                    </div>
                    <div class="ui segment" dir="rtl">
                        <strong>دانشگاه:</strong>
                        <strong>{{ ad.owner.profile.university }}</strong>
                    </div>
                    <div class="ui segment" dir="rtl">
                        <strong>قیمت: {{ ad.suggested_money }} تومان</strong>
                    </div>
                </div>
            </div>
        </div>

        <!-- long description -->
        <div class="item" dir="rtl">
            <strong>توضیحات:</strong>
            <div class="description" dir="rtl">
                {{ ad.description }}
            </div>
        </div>
    </div>
    <div class="ui divider"></div>
    {% if ad.owner is not None %}
    {% if ad.owner.id != request.user.id %}
    <div class="spaced" dir="rtl">
        <button class="green ui button" onclick="window.open('/chat/my_chatroom/{{ ad.owner.id}}')">
            ارتباط با اگهی دهنده
        </button>
    </div>
    {% endif %}
    {% endif %}
    <div class="ui divider"></div>
    {% if ad.owner == request.user %}
    <div class="spaced" dir="rtl">
        <button class="green ui button" onclick="window.open('/ads/{{ ad.id }}/edit')">
            ویرایش
        </button>
        <button class="red ui button" onclick="window.open('/ads/{{ ad.id }}/delete')">
            حذف
        </button>
    </div>
    <br>
    {% if ad.status == "ACCEPTED" %}
    <div class="spaced" dir="rtl">
        <form action="{% url 'user_score:set_addresser_and_done' ad_id=ad.id %}" method="POST">
            <!-- Security token -->
            {% csrf_token %}
            <!-- Using the formset -->
            <input type="text" placeholder="نام‌کاربری جواب دهنده آگهی" id="addresser_username"
                   name="addresser_username">
            <button class="red ui button" type="submit">
                خاتمه آگهی
            </button>

        </form>
    </div>
    {% elif ad.status == "DONE" %}
    <div class="spaced" dir="rtl">
        <div>
            <strong>
                پاسخ دهنده به آگهی:
            </strong>
        </div>
        <br>
        <strong>
            {{ ad.addresser.username }}
        </strong>

    </div>
    {% endif %}
    {% elif ad.addresser == request.user %}
    <div class="spaced" dir="rtl">
        <form action="{% url 'user_score:give_score' ad_id=ad.id %}" method="POST">
            <!-- Security token -->
            {% csrf_token %}
            <!-- Using the formset -->
            <input type="number" max="5" min="1" id="score" name="score" value="{{ ad.advertisement.score}}">
            <button class="red ui button" type="submit">
                امتیاز دادن
            </button>

        </form>
    </div>
    {% else %}
    None:)
    {% endif%}
</div>
{% endblock content %}

src/BookAdvertisement/templates/all_ads.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block extra_header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/all_ads.css' %}"/>
{% endblock %}

{% block content %}
    <div class="ui container">

        <div class="ui message">
            <h1 class="ui huge header">کتاب‌باز</h1>
            <p style="font-family: iransansdn; font-weight: bold" class="lead">
                مکانی برای تبادل کتاب های شما
            </p>
        </div>
    </div>
    <br>
    <div class="ui container" dir="rtl">
        <div class="ui relaxed divided items">
            <h2>{% trans "Search" %}</h2>
            <form class="ui form">
                <div class="field">
                    <label>{% trans "title" %}</label>
                    <input type="text" name="title__contains" placeholder="{% trans "title" %}">
                </div>
                <div class="field">
                    <label>{% trans "min cost" %}</label>
                    <input type="text" name="suggested_money__gte" placeholder="{% trans "minimum cost" %}" value="0">
                </div>
                <div class="field">
                    <label>{% trans "max cost" %}</label>
                    <input type="text" name="suggested_money__lte" placeholder="{% trans "maximum cost" %}" value="1000000">
                </div>
                <div class="field">
                    <label>{% trans "owner" %}</label>
                    <input type="text" name="owner__username__contains" placeholder="{% trans "owner username" %}">
                </div>
                <button class="ui button" type="submit">
                    {% trans "search" %}
                </button>
            </form>
        </div>
        <div class="ui divider"></div>
    </div>
    <div class="ui container">
        <div class="ui relaxed divided items">
            {% for ad in book_ads %}
                <div class="item">
                    <div href="/ads/{{ ad.id }}" class="ui small image">
                        {% if ad.poster.url is not None %}
                            <img src="{{ ad.poster.url }}" alt="Cinque Terre" width="600" height="400">
                        {% else %}
                            <img src="{% static 'images/default.jpg' %}" alt="Cinque Terre" width="600"
                                     height="400">
                        {% endif %}
                    </div>
                    <div class="content">
                        <a target="_blank" href="/ads/{{ ad.id }}" class="header">{{ ad.title }}</a>
                        <div class="meta">
                            <a>{{ ad.author }}</a>
                        </div>
                        <div class="description">{{ ad.description }}</div>
                        <div class="extra">
                            <a target="_blank" href="/ads/{{ ad.id }}" class="ui right floated primary button">
                                اطلاعات بیشتر
                                <i class="right chevron icon"></i>
                            </a>
                            {% if ad.sell %}
                                <div class="ui label">فروش</div>
                            {% else %}
                                <div class="ui label">خرید</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="clearfix"></div>


{% endblock content %}