src/BookAdvertisement/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import get_all_ads, get_ad_info, AdCreate, AdUpdate, AdDelete, \
    get_all_pending_ads_for_admin, update_ad_status

app_name = 'BookAdvertisement'

urlpatterns = [
    path('', get_all_ads, name='all-ads'),
    path('pending/', get_all_pending_ads_for_admin, name='all-pending-ads'),
    path('pending/<int:ad_id>/<str:accept>/', update_ad_status, name='update-pending-ad-status'),
    path('<int:pk>/', get_ad_info, name='ad'),
    path('<int:pk>/edit', login_required(AdUpdate.as_view()), name='ad-update'),
    path('<int:pk>/delete', login_required(AdDelete.as_view()), name='ad-delete'),
    path('new/', login_required(AdCreate.as_view()), name='ad-new'),
]

src/accounts/urls.py
from django.urls import path, reverse_lazy
from accounts import views
from django_registration.backends.activation.views import RegistrationView, ActivationView
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/',
        RegistrationView.as_view(success_url=reverse_lazy('accounts:login')),
        name='register'),
    path('activate/<str:activation_key>/',
        ActivationView.as_view(success_url=reverse_lazy('accounts:login')),
        name="activate",
    ),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('profile/edit/', views.edit_profile_view, name='edit'),
    path('profile/my/', views.my_profile_view, name='my_profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
]

src/home_page/urls.py
from django.urls import path
from .views import home_page_view
app_name = 'home_page'


urlpatterns = [
    path('', home_page_view, name='home'),
]

src/napela/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('chat/', include('chat_channel.urls')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ads/', include('BookAdvertisement.urls', namespace='BookAdvertisement')),
                  path('score/', include('user_score.urls', namespace='user_score')),
                  path('', include('home_page.urls', namespace='home_page'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no"
    />
    <meta
            name="description"
            content="Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI."
    />
    <meta name="keywords" content="Semantic-UI, Theme, Design, Template"/>
    <meta name="author" content="PPType"/>
    <meta name="theme-color" content="#ffffff"/>
    <title>{{ page_title }}</title>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
            type="text/css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontiran.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dist/semantic.css' %}"/>
    {% block extra_header %}{% endblock extra_header %}


</head>

<body id="root">
<div class="ui tablet computer only padded grid">
    <div class="ui top fixed borderless fluid huge menu">
        <div class="ui container">
        <a class="link mobile hidden item" href="/">
                <img src="/static/images/logo1.png" style="width: 70px"></a>
            <a href="/" class="header item">کتاب‌باز</a>
            <div class="right menu">
                {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}"
                       class="item">{% trans 'logout' %}</a>
                    <a href="{% url 'accounts:my_profile' %}"
                       class="item">{% trans 'my profile' %}</a>
                {% else %}
                    <a href="{% url 'accounts:register' %}"
                       class="item">{% trans 'register' %}</a>
                    <a href="{% url 'accounts:login' %}"
                       class="item">{% trans 'login' %}</a>
                {% endif %}
                <a href="{% url 'BookAdvertisement:ad-new' %}"
                   class="item">{% trans 'add ad' %}</a>
                <a href="{% url 'BookAdvertisement:all-ads' %}"
                   class="item">{% trans 'ads list' %}</a>
                <a href="{% url 'home_page:home' %}"
                   class="item">{% trans 'home' %}</a>
            </div>
        </div>
    </div>
</div>


{% block content %}{% endblock content %}

</body>
</html>